
model: 'asdgan'
checkname: 'asdgan'
dataset: 'brats_t2'
data_dir: "./../../../data/brats"
partition_method: 'hetero'
client_num_in_total: 3
client_num_per_round: 3
gpu_mapping_file: "../gpu_mapping.yaml"
gpu_mapping_key: 'mapping_config_sense02_3'
save_client_model: true

sample_method: 'uniform'
batch_size: 30
client_optimizer: 'adam'
lr: 0.001

beta1: 0.5
momentum: 0.9
weight_decay: 5.e-4
nesterov: false

epochs: 200
evaluation_frequency: 5
dl_num_workers: 0
input_nc: 1
output_nc: 1
ngf: 64
ndf: 64
gan_mode: 'vanilla'
netG: 'unet_256'
netD: 'basic'
n_layers_D: 3
norm: 'batch'
init_type: 'normal'
init_gain: 0.02
no_dropout: false

lambda_L1: 20
lambda_perceptual: 1
lambda_G: 0.2
lambda_D: 0.1
pool_size: 0
lr_policy: 'linear'
epoch_count: 1
niter: 200
niter_decay: 200
lr_decay_iters: 50
lr_decay_gamma: 0.1
verbose: false

continue_train: false
brain_mask_input: 1
brain_mask_noise: 0.
mask_L1_loss: false

backbone_freezed: false
sync_bn: false
freeze_bn: false

up_mode: transpose